[project]
name = "shaktiai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "fastapi>=0.117.1",
    "httpx>=0.28.1",
    "numpy>=2.3.3",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
